[2024-11-11T21:41:02.647+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-11T21:41:02.653+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-28T00:00:00+00:00 [queued]>
[2024-11-11T21:41:02.656+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-28T00:00:00+00:00 [queued]>
[2024-11-11T21:41:02.656+0000] {taskinstance.py:2866} INFO - Starting attempt 4 of 5
[2024-11-11T21:41:02.660+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_book_data> on 2024-06-28 00:00:00+00:00
[2024-11-11T21:41:02.670+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=153) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-11T21:41:02.671+0000] {standard_task_runner.py:72} INFO - Started process 154 to run task
[2024-11-11T21:41:02.673+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_amazon_books', 'fetch_book_data', 'scheduled__2024-06-28T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmpm_yp3bz1']
[2024-11-11T21:41:02.674+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask fetch_book_data
[2024-11-11T21:41:02.705+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-28T00:00:00+00:00 [running]> on host 1c507ca650f0
[2024-11-11T21:41:02.741+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_amazon_books' AIRFLOW_CTX_TASK_ID='fetch_book_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-28T00:00:00+00:00'
[2024-11-11T21:41:02.742+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-11T21:41:02.742+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-11T21:41:02.743+0000] {logging_mixin.py:190} INFO - Current task name:fetch_book_data state:running start_date:2024-11-11 21:41:02.653837+00:00
[2024-11-11T21:41:02.743+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_amazon_books and current dag run status:running
[2024-11-11T21:41:02.743+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-11T21:41:04.629+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-11T21:41:04.633+0000] {taskinstance.py:2603} INFO - Dependencies not met for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-28T00:00:00+00:00 [restarting]>, dependency 'Task Instance State' FAILED: Task is in the 'restarting' state.
[2024-11-11T21:41:04.638+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
[2024-11-11T21:41:04.888+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-11T21:41:04.897+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-11T21:41:04.897+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-28T00:00:00+00:00, execution_date=20240628T000000, start_date=20241111T214102, end_date=20241111T214104
[2024-11-11T21:41:04.905+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-11T21:41:04.906+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-11T21:41:04.906+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_amazon_books queued_at:2024-11-11 21:29:13.177014+00:00
[2024-11-11T21:41:04.907+0000] {logging_mixin.py:190} INFO - Task hostname:1c507ca650f0 operator:PythonOperator
[2024-11-11T21:41:04.916+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-11T21:41:04.946+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-11T21:41:04.947+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
